CREATE DATABASE DETShop
GO

CHECKPOINT 

USE DETShop
GO

CREATE TABLE Users(
	USERNAME	VARCHAR(30)		NOT NULL,
	PASS		VARCHAR(100)	NOT NULL,
	OTP			VARCHAR(100),

	PRIMARY KEY (USERNAME),
);

CREATE TABLE Produto(
	NOME		VARCHAR(30)		NOT NULL,
	PRECO		FLOAT,
	QUANTIDADE	INT,

	PRIMARY KEY (NOME)
);

CREATE TABLE Review(
	NOME_U		VARCHAR(30),
	NOME_P		VARCHAR(30),
	N_STARS		INT				CHECK(N_STARS > 0),
	COMENTARIO	VARCHAR(300),

	PRIMARY KEY (NOME_U, NOME_P),
	FOREIGN KEY (NOME_U) REFERENCES Users (USERNAME),
	FOREIGN KEY (NOME_P) REFERENCES Produto (NOME)
);

CREATE TABLE Historico(
	DATA_COMPRA	DATE,
	N_CARRINHO	INT				NOT NULL	IDENTITY(1,1),
	PRECO_TOTAL INT,

	PRIMARY KEY (N_CARRINHO)
);

CREATE TABLE Carrinho(
	N_COMPRA	INT				NOT NULL,
	NOME_P		VARCHAR(30),
	STOCK		INT				NOT NULL	CHECK(STOCK > 0),

	FOREIGN KEY (N_COMPRA) REFERENCES Historico (N_CARRINHO),
	FOREIGN KEY (NOME_P) REFERENCES Produto (NOME)
);